Fix/workaround dependency vulnerabilities
- bump api-helper-java to 3.0.2 to fix
  - CVE-2025-48924
- bump api-sdk-manager-java-library to 3.0.11
  - removes dependency on commons-lang and fixes runtime java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
- bump spring-boot to 3.5.5 to fix
  - CVE-2025-41242
  - CVE-2025-48989
- bump structured-logging to 3.0.39
- bump api-enumerations to master latest
- bump sonar-maven-plugin to 5.2.0.4988
- attempt fix to missing dependency report on sonarqube server:
  - add property sonar.dependencyCheck.htmlReportPath with standard value
  - remove sonar.dependencyCheck.htmlReportPath from sonar target